namespace BuilderGenerator
{
    internal class Templates
    {
        public const string GeneratedAttribute = "[GeneratedCode(\"BuilderGenerator\", \"1.0\")]";

        public const string PropertyTemplate = @"        public Lazy<{{PropertyType}}> {{PropertyName}} = new Lazy<{{PropertyType}}>(() => default({{PropertyType}}));";

        public const string BuildMethodTemplate = @"
        {{GeneratedAttribute}}
        public override {{ClassFullName}} Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<{{ClassFullName}}>(() => 
                {
                    var result = new {{ClassFullName}} 
                    {
{{Setters}}
                    };

                    return result;
                });

                if (PostProcessAction != null)
                {
                    PostProcessAction(Object.Value);
                }
            }

            return Object.Value;
        }";

        public const string BuildMethodSetterTemplate = "                        {{PropertyName}} = {{PropertyName}}.Value,";

        public const string WithPostProcessActionTemplate = @"
        {{GeneratedAttribute}}
        public {{BuilderName}} WithPostProcessAction(Action<{{ClassFullName}}> action)
        {
            PostProcessAction = action;

            return this;
        }

        {{GeneratedAttribute}}
        public T WithPostProcessAction<T>(Action<{{ClassFullName}}> action) where T : {{BuilderName}}
        {
            PostProcessAction = action;

            return (T)this;
        }";

        public const string WithMethodTemplate = @"
        {{GeneratedAttribute}}
        public {{BuilderName}} With{{PropertyName}}({{PropertyType}} value)
        {
            return With{{PropertyName}}(() => value);
        }

        {{GeneratedAttribute}}
        public {{BuilderName}} With{{PropertyName}}(Func<{{PropertyType}}> func)
        {
            {{PropertyName}} = new Lazy<{{PropertyType}}>(func);
            return this;
        }

        {{GeneratedAttribute}}
        public {{BuilderName}} Without{{PropertyName}}()
        {                    
            {{PropertyName}} = new Lazy<{{PropertyType}}>(() => default({{PropertyType}}));
            return this;
        }";


        public const string BuilderClassTemplate =
@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the data builder generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using BuilderGenerator.Common;
{{UsingBlock}}

namespace {{Namespace}}
{
    {{GeneratedAttribute}}
    public partial class {{BuilderName}} : Builder<{{ClassFullName}}>
    {
        public Action<{{ClassFullName}}> PostProcessAction { get; set; }
{{Properties}}
{{BuildMethod}}
{{WithMethods}}
    }
}";
    }
}
