name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        working-directory: ./src

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}

    - name: Build solution
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}

    #- name: Test solution
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ${{env.working-directory}}
