name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      working-directory: ./src

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out source
      uses: actions/checkout@v4

    # Install SDKs
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Build and Test    
    - name: Restore dependencies
      run: dotnet restore --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Build solution
      run: dotnet build --configuration Release --no-restore  --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Test solution
      run: dotnet test --configuration Release --no-restore --no-build --verbosity minimal
      working-directory: ${{env.working-directory}}