name: Release

on:
  release:
    types: [published]

jobs:
  build:
    env:
      working-directory: ./src

    runs-on: ubuntu-latest
   
    steps:
    - name: Check out source
      uses: actions/checkout@v3

    # Install SDKs
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Build and Test
    - name: Restore dependencies
      run: dotnet restore --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Build solution
      run: dotnet build --configuration Release --no-restore  --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Test solution
      run: dotnet test --configuration Release --no-restore --no-build --verbosity minimal
      working-directory: ${{env.working-directory}}

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build --output . --verbosity normal
      working-directory: ${{env.working-directory}}

    - name: Push
      run: dotnet nuget push "*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
      working-directory: ${{env.working-directory}}
